### ISSUE TITLE
管理员编辑的时候，所属权限组显示不全

### ISSUE THREAD

**Issue by okmylove** [xiayulei/think_admin#11]
管理员编辑的时候，所属权限组显示不全（应该是外层div没有撑开。）没想到咋弄。

**Comment by yangedu** [comment]
#2 管理员已回复了

> 这个问题在官方的社区里有人也提到了，说是被tab容器遮掩了，给那段 tab容器加上下面的style：

`<div class="layui-tab layui-tab-brief" style="overflow: visible;">`
> 看着官方的layui紧急更新到了1.0.7，不知道修复了这个问题没有，你可以下载直接替换掉layui，我这边在补充后台功能，完善上传、编辑器之类的，稍后会一起更新。

**Comment by xyl-tools** [comment]
@yangedu 感谢回答！
