### ISSUE TITLE
实际使用过程中发现的小反馈

### ISSUE THREAD

**Issue by zhangshuren** [xiayulei/think_admin#16]
- 我在添加导航时加了个关联栏目的弹窗，
在加载弹窗的请求中，调用了两次系统公共函数array2level()，
（/admin/controller/Nav.php文件的构造函数一次，自己写的控制器方法中调用了一次）
由于这个函数的输出结果$list变量用到了static类型，这样如果在一个请求中多次调用了这个函数，
最后$list的结果就会包含每次调用该函数的结果

- 在HomeBase.php文件中获取前端导航列表时，getNav()调用array2tree()处理后输出的导航列表顺序会出现不是预期的情况

**Comment by xyl-tools** [comment]
@zhangshuren 感谢您的认真反馈，array2level函数确实存在这个情况，目前还没想到更好的解决方案，补丁措施目前想到的是可以在模型中使用方法重写array2level的功能。前端导航调用时，因为默认的排序值为0，排序时会有异常，可以给排序默认初始值赋值为大于0的数字，后续版本将会针对这个问题做优化。

**Comment by zhangshuren** [comment]
@xiayulei  嗯，对于array2level函数我现在的方法是把$list引用作为函数默认函传进去的，
形如这样子：`function array2level($array, $pid = 0, $level = 1, &$list=[]){...}`

array2tree()函数的替代方案我用的是onethink的list_to_tree()函数。
另外希望能一起加入进来开发你的这个项目，因为这个项目给我的感觉和我自己的一些想法很契合，
而且看得出你在做这个项目的时候很是用心。

**Comment by xyl-tools** [comment]
@zhangshuren 传参的方式也是个办法，有意向开发的话，可以fork一份，到时候提交个pull request，我会合并请求的。

**Comment by zhangshuren** [comment]
@xiayulei 好的！你可以把你自己的规划列出来吖，然后我们可以更有针对性的去提交自己的修改

**Comment by xyl-tools** [comment]
@zhangshuren 嗯，后期我整理个TODO列表出来放在上面。

**Comment by RoseKissYou** [comment]
这个权限反馈好像提示没有rules,rules字段默认是不能为空的, 添加数据的时候是不是要遍历rules表选择权限组所拥有的权限啊

**Comment by xyl-tools** [comment]
@RoseKissYou 权限rules字段可以为空，就是权限组初始未授权状态，权限更新变动会更新rules字段。
