### ISSUE TITLE
你好，楼主

### ISSUE THREAD

**Issue by jameshuimin** [xiayulei/think_admin#17]
11

**Comment by xyl-tools** [comment]
请看安装说明，git克隆下来以后，需要执行composer install安装，默认是没有vendor目录的，captcha_src函数就是验证码类库

2017-04-19 20:07 GMT+08:00, jameshuimin <notifications@github.com>:

**Comment by jameshuimin** [comment]
你好，我的安装步骤是这样：下载压缩包(不是克隆下载)，然后本地数据库加入数据库，URL重写等，再运行 重定向的域名/admin  ；
请问我少了什么步骤呢？

**Comment by xyl-tools** [comment]
@jameshuimin 已下载完整压缩包本地测试无问题，查看vendor目录是否存在，URL重写是否正确，或者在官网重新下载安装包测试，如有问题，再贴一下错误。

**Comment by jameshuimin** [comment]
vendor这个目录没存在，URL重写应该是正常的，因为我用重定向的域名是可以访问到的。

**Comment by jameshuimin** [comment]
如果上传视频该怎么改呢

**Comment by jameshuimin** [comment]
111
