### ISSUE TITLE
添加，编辑管理员时权限组选项被遮挡

### ISSUE THREAD

**Issue by yangedu** [xiayulei/think_admin#2]
谢谢博主的分享 。
在添加管理员选择权限组时，由于权限组比较多，下拉之后被父级的div遮挡住了。
这个在靠近底部的下拉框可能都会出现，现在只是把下拉菜单上移其他选项之前才显示全部的选项

**Comment by xyl-tools** [comment]
这个问题在官方的社区里有人也提到了，说是被tab容器遮掩了，给那段 tab容器加上下面的style：
```
<div class="layui-tab layui-tab-brief" style="overflow: visible;">
```
看着官方的layui紧急更新到了1.0.7，不知道修复了这个问题没有，你可以下载直接替换掉layui，我这边在补充后台功能，完善上传、编辑器之类的，稍后会一起更新。

**Comment by yangedu** [comment]
谢谢

**Comment by xyl-tools** [comment]
@yangedu 客气，也感谢你的反馈
