### ISSUE TITLE
database.php文件

### ISSUE THREAD

**Issue by onenook** [xiayulei/think_admin#21]
经过排查，这个文件可能导致后台验证码不显示，里面的代码没有问题，文件本身可能有问题，重新建一个文件把代码复制进去就正常了，不知道这是什么情况，哪位大哥可以解释一下

**Comment by xyl-tools** [comment]
本地排查并无问题，可以使用清除BOM头工作整体清除一下你的代码文件，看看是否是因为这方面原因引起的

在 2017/5/31，onenook<notifications@github.com> 写道：
