### ISSUE TITLE
后台管理能改用tab显示各项功能菜单么？

### ISSUE THREAD

**Issue by wooddoor** [xiayulei/think_admin#22]
如上，有些功能实现用tab显示要方便很多。

另外，在登录页面，如果用户名或密码错误没有登录成功，是否应该跟着自动更新一下验证码呢？现在是登录失败后再次登录就必须要手动刷新验证码，比较麻烦。

**Comment by xyl-tools** [comment]
tab切换方式，可以自己在layui官方找模板，有做好的类似的后台模板，自己手动替换即可，至于后台验证码不自动刷新，是故意做成这样，防止恶意登录，你可以根据返回状态判断，在JS中做刷新操作。

在 2017/6/7，增城-柴门<notifications@github.com> 写道：

**Comment by wooddoor** [comment]
这样要手动刷新验证码，如果是对于机器自动登录来说好像也没什么用吧？但是对正常用户感觉还是有些麻烦的。
