### ISSUE TITLE
为什么入口文件要放在根目录？

### ISSUE THREAD

**Issue by shenfeng07** [xiayulei/think_admin#23]
我有个疑问，为什么入口文件要放在根目录，这样不会不安全吗？

**Comment by xyl-tools** [comment]
国情问题，国内很多开发者还是使用虚拟主机的多数，虚拟主机上很难做到二级目录的入口部署，为了兼容考虑。

2017-06-13 15:45 GMT+08:00, shenfeng07 <notifications@github.com>:
