### ISSUE TITLE
select点击触发事件

### ISSUE THREAD

**Issue by 272361997** [xiayulei/think_admin#24]
admin.js文件
form.on('select(ajax_change)', function (data) {
    $.ajax({
        url: data.form.action,
        type: data.form.method,
        data: $(data.form).serialize(),
        success: function (info) {
                setTimeout(function () {
                    location.href = info.url;
                }, 1000);
            layer.msg(info.msg);
        }
    });

    return false;
});
select 标签 <select name="type" lay-filter="ajax_change">
点击后报错 ：TypeError: data.form is undefined
请问我该如何解决 初次用layui望指教。

**Comment by xyl-tools** [comment]
非程序BUG方面的错误，请勿以issues方式提交，详情可以参考LayUI官方开发手册。

2017-06-14 9:30 GMT+08:00, 272361997 <notifications@github.com>:
