### ISSUE TITLE
在nginx上用不了  

### ISSUE THREAD

**Issue by Tiamo1221** [xiayulei/think_admin#26]
在apache 上运行正常的  咋ngin上就运行不了

**Comment by xyl-tools** [comment]
nginx需要自己配置URL重写规则

2017-08-10 19:53 GMT+08:00, Tiamo1221 <notifications@github.com>:

**Comment by Tiamo1221** [comment]
什么时候能加上图表统计？这个在后台用的也比较多

**Comment by xyl-tools** [comment]
无需处理
