### ISSUE TITLE
删除父菜单的时候子菜单不会一块删除

### ISSUE THREAD

**Issue by guandaxia** [xiayulei/think_admin#3]
在菜单管理删除菜单的时候，当该菜单有子菜单时，并不会提示，而是直接删除父菜单，子菜单还在。这样菜单管理里是看不到父菜单和子菜单了，但是权限管理里面还是会有没有删除的子菜单。

   /**
     * 删除菜单
     * @param $id
     */
    public function delete($id) {
        if ($this->auth_rule_model->destroy($id)) {
            $this->success('删除成功');
        } else {
            $this->error('删除失败');
        }
    }

目前的删除菜单是这么处理的。

菜单管理就是这么设计的吗？

**Comment by xyl-tools** [comment]
@guandaxia 感谢反馈，这个BUG将在下一个版本中修复，你可以在删除前做个判断。

**Comment by guandaxia** [comment]
@xiayulei 嗯，我现在就是删除的时候把子菜单找出来，一块删除了。
