### ISSUE TITLE
后台左侧子菜单的active

### ISSUE THREAD

**Issue by Robbin-Sun** [xiayulei/think_admin#31]
后台左侧子菜单的active样式是不是根据controller来添加的，我现在遇到一个问题：后台一个父菜单下面有三个子菜单，是同一个controller下面三个不同的action，现在点击激活其中一个action，css会自动给另外两个action加active样式，这样看上去就是同时激活了三个action。不知道能否改成根据action来添加active样式。

**Comment by xyl-tools** [comment]
这块目前需要自行修改，激活样式以是控制器名区分的，可以在admin.js文件中调整高亮部分的判断。

在 2018/4/11，孙中杰<notifications@github.com> 写道：

**Comment by Robbin-Sun** [comment]
好的，谢了，这块已经弄好了
