### ISSUE TITLE
添加权限组报错提示500

### ISSUE THREAD

**Issue by anglesdl** [xiayulei/think_admin#5]
在添加权限组页面输入名称后，提交没有反应，
在Console提示”POST http://localhost/index.php/admin/auth_group/save.html 500 (Internal Server Error)“。这是怎么一回事？

**Comment by xyl-tools** [comment]
@anglesdl 500错误为服务器错误，一般是程序执行出错，可以查看下详细的报错信息，我这边测试无问题。
