### ISSUE TITLE
该更新一下了 加入插件机制 另外后台的栏目是不是有问题 我感觉 一级栏目不应该可以加内容 只有最终的栏目才可以加内容 编辑器更换为百度的吧

### ISSUE THREAD

**Issue by suifeng168** [xiayulei/think_admin#6]
该更新一下了 加入插件机制 另外后台的栏目是不是有问题 我感觉 一级栏目不应该可以加内容 只有最终的栏目才可以加内容 编辑器更换为百度的吧
而且最终的栏目也不能加子栏目了 再加一个单页
增加一个模板切换 增加一个文章模型

**Comment by xyl-tools** [comment]
@q889518 栏目本身就带单页功能，选择类型为单页，然后在前端自己根据类型调用内容就可以了，编辑器将在下一版本中更换为Kindeditor，百度编辑器过滤的东西太多，有兴趣的话你可以自己更换一下，至于文章模型之类的目前不考虑增加，这是个后台管理系统，目的在于节省开发后台基础功能的时间，定制的越多反而限制越多，有兴趣可以fork一份协作开发。
