### ISSUE TITLE
本地部署好后没有跳转到登录界面， 访问提示如下

### ISSUE THREAD

**Issue by chaofan2014** [xiayulei/think_admin#7]
Think Admin 1.0

后台演示：http://xiyilou.com/index.php/admin

演示账号：demo demo

Github：https://github.com/xiayulei/think_admin

**Comment by chaofan2014** [comment]
现在可以通过http://localhost/master/index.php/admin访问，界面是纯文字，是不是跟演示版不一样

**Comment by xyl-tools** [comment]
@chaofan2014 资源路径修改一下，你部署到了二级目录里，初始版本没有考虑二级目录的问题，后台引用资源都是/public开始查找的
