### ISSUE TITLE
本地部署后跟提供的源码不一致

### ISSUE THREAD

**Issue by liwei3gjob** [xiayulei/think_admin#8]
该版本提供的源代码：
1）数据库用户名为test     不是demo
2)  登陆界面是纯文字版（很丑），跟演示的demo（登陆界面效果）不一致
3）数据库配置后，一直无法登陆成功，还希望能够把配置简要写一些

建议：提供一份你的演示版的源代码吧，大家都是看了你的演示版才决定研究你的源代码，所以别忽悠大家啊

**Comment by xyl-tools** [comment]
@liwei3gjob 
1、数据库用户名demo是我线上演示的账号，不是本地数据库创建的账号，本地默认账号是admin，请仔细阅读文档说明。
2、登陆界面显示纯文字，是因为你把站点配置到二级目录去了吧？使用二级目录，默认的CSS、JS文件路径加载就不对了，可以手动修改下，建议调试这种动态站点，还是单独配置一个虚拟主机来测试比较好。
3、数据库配置后，无法登陆成功，请打开浏览器控制台查看具体错误，不然无法判断你说明的情况

**Comment by liwei3gjob** [comment]
好的，非常感谢，我再试下~


原始邮件
发件人:xiayuleinotifications@github.com
收件人:xiayulei/think_adminthink_admin@noreply.github.com
抄送:liwei3gjobliwei3gjob@163.com; Mentionmention@noreply.github.com
发送时间:2016年12月12日(周一) 09:05
主题:Re: [xiayulei/think_admin] 本地部署后跟提供的源码不一致 (#8)


@liwei3gjob
 1、数据库用户名demo是我线上演示的账号，不是本地数据库创建的账号，本地默认账号是admin，请仔细阅读文档说明。
 2、登陆界面显示纯文字，是因为你把站点配置到二级目录去了吧？使用二级目录，默认的CSS、JS文件路径加载就不对了，可以手动修改下，建议调试这种动态站点，还是单独配置一个虚拟主机来测试比较好。
 3、数据库配置后，无法登陆成功，请打开浏览器控制台查看具体错误，不然无法判断你说明的情况
